### PR TITLE
Readme update

### PR DESCRIPTION
**Pull request by emem365**
Updating the ReadMe.
Also solves #3

### CODE REVIEW

**Comment by ajay-prabhakar** [comment]
@emem365 thanks for your valuable contribution :tada:

just some quick reviews
- Remove kotlin badge as most will contain only flutter 
- Add some badge like representing designs 

Capture

- In the above picture packages we are using is mixed with table please fix that 
- Use only one term for now use *packages in use* 
 
Capture

- Please give a new line after fear emoji
- And Please add some descriptions for each designs

**Comment by emem365** [comment]
> - [x] Remove kotlin badge as most will contain only flutter

Done
> - [ ] Add some badge like representing designs

About this. Could you suggest something you had in mind? shields.io uses icons from [simple-icons](https://simpleicons.org/). Maybe have a look. We can add any text we like.
> - [x] In the above picture packages we are using is mixed with table please fix that
> - [x] Use only one term for now use packages in use
> - [x] Please give a new line after fear emoji

These are done as well
> - [ ] And Please add some descriptions for each designs

For this, tbh, I'll have to take a look through all your screens myself. and tbh the gifs and the screenshot make it pretty self explanatory, and pretty much dont need a description. Maybe we could add something later :)

**Comment by ajay-prabhakar** [comment]
I don't have anything in my mind currently, 
for now, it is fine

**Review by ajay-prabhakar — APPROVED** [review]
looking forward to your contributions 😄

**Comment by ajay-prabhakar** [comment]
May be can you add the contribution guidelines and license

**Comment by emem365** [comment]
I am not sure if I can find time to write a Contributors guide right now. Maybe sometime later.

And for the license file:
1. Go to your repo
2. Add a file
3. Name it LICENSE
 _You will find that on the right side of text box for name of the file, there is an option to choose a license,_ 
4. Choose one which meets your needs(For most projects an Apache License is just fine)
5. You'll need to put in your name and the year, and you're good to go

**Comment by ajay-prabhakar** [comment]
It fine,
I know how to add the lisence, I added the issue because someone who interested can contribute

**Pull request merged**
